export enum CurrencyType {
    Money = "Money",
    Souls = "Souls",
    Wood = "Wood",
    Grain = "Grain",
    Bronze = "Bronze",
    Silver = "Silver",
    Gold = "Gold",
    Salt = "Salt",
    Diamond = "Diamonds",
    Scrap = "Scrap",
    Gasoline = "Gasoline",
    Oil = "Oil",
    Lightning = "Lightning",
    Plutonium = "Plutonium",
}
